services:
  db:
    image: mariadb:10.11
    environment:
      - 'MARIADB_DATABASE=nicopico_n2rss'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=n2rss'
    ports:
      - '3306:3306'
    volumes:
      - db:/data/db
volumes:
  db:
    driver:
      local
