###
GET http://localhost:8080/rss

### Stop server (fails)
POST http://localhost:8080/stop
X-Secret-Key: pouet

### Stop server (success)
POST http://localhost:8080/stop
X-Secret-Key: abcd

### Content-Type
GET http://localhost:8080/rss/pointer

### Request
POST http://localhost:8080/send-request
Content-Type: application/x-www-form-urlencoded

newsletterUrl = https://www.some.fo
