name: CI - Check Pull Requests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'act/**'
      - 'deploy/**'
      - 'stubs/**'
      - 'support/**'
      - '*.md'

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon build
      - name: Run unit-tests
        run: ./gradlew --no-daemon test --info
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'server/build/test-results/test/**.xml'
      - name: Check Coverage
        run: ./gradlew --no-daemon koverXmlReport koverVerify
      - name: Add coverage report
        uses: mi-kas/kover-report@v1
        if: always()
        with:
          path: |
            ${{ github.workspace }}/server/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
